config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  # get 'reservations/:id/braintree/new' => "braintree#new", as: :new_braintree
  post 'braintree/checkout'
  get 'welcome/index'

  root "welcome#index"
  # get '/' => "welcome#index", as: 'root'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, controller: "listings", only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reservations, only: [:create, :index]
    # resources :reservations only: [:index,:create] # do that to show the reservations under listing/:id and create a reservation under listing/:id
  end

  resources :reservations, except: [:new, :create]
  # resources :reservations only: [:show, :edit, :update] # to show the reservation page, to edit and update reservation

  resources :users, controller: "users", only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :password, # user can only have one password therefor resource without a s
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings # user can have a lot of lisitings therefore resources with a s
    resources :reservations, only: [:index] # to show user's reservations
  end



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :title, presence: true
  validates :address, presence: true
  validates :pax, presence: true
  validates :room_number, presence: true
  validates :bed_number, presence: true
  validates :price, presence: true
  validates :country, presence: true
  validates :state, presence: true
  validates :city, presence: true
  validates :zipcode, presence: true
  validates :description, presence: true
  validates :property_type, presence: true
  
  belongs_to :user
  has_many :reservations, dependent: :destroy
  mount_uploaders :photos, PhotoUploader
  serialize :photos, Array

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    if params[:user_id] # if there is user_id
      @listings = User.find(params[:user_id]).listings # this is to show one user's all listings
    else
      @listings = Listing.all # this is to show all user's listings
    end
  end

  def show
    @listing = Listing.find(params[:id]) # find the users/user_id/listings/:id and show in show.html.erb
    @reservation = Reservation.new
    # cause render form in the listing/show page, need to know what @reservation is sp define it here
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params) # strong params, user can only key in the params require so hackers cannot hack
    @listing.user = current_user
    # byebug
    if @listing.save
      redirect_to @listing # redirect to controller show to show the new listing
      flash[:success] = "List successfully created!"
    else
      flash[:fail] = @listing.errors.full_messages
      render 'new' # render to 'new.html'
    end
  end

  def edit
    @listing = Listing.find(params[:id]) # find the users/user_id/listings/:id
  end

  def update
    @listing = Listing.find(params[:id]) # find the users/user_id/listings/:id
    @listing.user = current_user
    if @listing.update(listing_params) # strong params, user can only key in the params require so hackers cannot hack
      flash[:success] = "Successfully updated your listing"
      redirect_to @listing # redirect to controller show to show the new listing
    else
      flash[:error] = "Error updating lisitng"
      render 'edit' # render to controller 'edit.html'
    end
  end

  def destroy
    @listing = Listing.find(params[:id]) # find the users/user_id/listings/:id
    @listing.destroy
    flash[:delete] = "Successfully deleted!"
    redirect_to user_listings_path
  end

# strong params to prevent hacker hack into your system
private
  def listing_params
    params.require(:listing).permit(:title, :address, :pax, {photos: []}, :state, :city, :zipcode, :country, :bed_number, :room_number, :property_type, :description, :price)
  end
end

app/helpers/listing_helper.rb
module ListingHelper
end

app/views/listings/_form.html.erb
<p>Key in the details of your listings </p>

<%= form_for @listing do |form| %>
  <p>
    <div>
      <%= form.label "Title: " %>
      <%= form.text_field :title %>
    </div>
    <br>
    <div>
      <%= form.label "Address: " %>
      <%= form.text_field :address %>
    </div>
    <br>
    <div>
      <%= form.label "State: " %>
      <%= form.text_field :state%>
    </div>
    <br>
    <div>
      <%= form.label "City: " %>
      <%= form.text_field :city%>
    </div>
    <br>
    <div>
      <%= form.label "Zipcode: " %>
      <%= form.text_field :zipcode%>
    </div>
    <br>
    <div>
      <%= form.label "Country: " %>
      <%= form.text_field :country %>
    </div>
    <br>
    <div>
      <%= form.label "Pax Number: " %>
      <%= form.text_field :pax %>
    </div>
    <br>
    <div>
      <%= form.label "Bed Number: " %>
      <%= form.text_field :bed_number%>
    </div>
    <br>
    <div>
      <%= form.label "Room Number: " %>
      <%= form.text_field :room_number %>
    </div>
    <br>
    <div>
      <%= form.label "Property Type: " %>
      <%= form.text_field :property_type %>
    </div>
    <br>
    <div>
      <%= form.label "Description: " %>
      <%= form.text_field :description %>
    </div>
    <br>
    <div>
      <%= form.label "Price: " %>
      <%= form.text_field :price %>
    </div>
    <br>
    <div>
      <%= form.label "Photos: " %>
      <%= form.file_field :photos, multiple: true %>
    </div>
  </p>

  <p>
    <%= form.submit "Submit Listing!" %>
  </p>
<% end %>

app/views/listings/edit.html.erb
<h1>Listing#edit</h1>
<p>Find me in app/views/listing/edit.html.erb</p>

<%= render 'form' %>

app/views/listings/index.html.erb
<h1> Listings </h1>

<table class="table">
  <tr>
    <th>Listing</th>
    <th>Address</th>
    <th>State</th>
    <th>City</th>
    <th>Zipcode</th>
    <th>Country</th>
    <th>Photos</th>
    <th>Pax</th>
    <th>Bed Number</th>
    <th>Room Number</th>
    <th>Property Type</th>
    <th>Description</th>
    <th>Price</th>
    <th></th>
    <th></th>
  </tr>
  <% @listings.each do |l| %>
    <tr>
      <td> <%= link_to l.title, listing_path(l.id) %> </td>
      <td> <%= l.address %> </td>
      <td> <%= l.state %> </td>
      <td> <%= l.city %> </td>
      <td> <%= l.zipcode %> </td>
      <td> <%= l.country %> </td>
      <td> <% l.photos.each do |photo| %>
           <%= image_tag photo.medium, class: "img-response" %>
           <% end %>
      <td> <%= l.pax %> </td>
      <td> <%= l.bed_number %> </td>
      <td> <%= l.room_number %> </td>
      <td> <%= l.property_type %> </td>
      <td> <%= l.description %> </td>
      <td> <%= l.price %> </td>
      </td>
      <!-- one way to make chewbacca and yodamaster admin -->
      <% if current_user.email == "chewbacca@email.com" || "yodamaster@email.com" %>
      <!-- to find the current_user and then the listing id, current_user is auto defined in rails -->
      <td> <%= link_to "Edit", edit_user_listing_path(current_user, l.id) %> </td>
      <!-- to make it to the method delete, data is to have the pop out box with the message -->
      <td> <%= link_to "Delete", user_listing_path(current_user, l.id), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      <% end %>
    </tr>
  <% end %>
</table>

<p>Listing#index</p>

app/views/listings/new.html.erb
<h1> Make a new listing </h1>

<%= render 'form' %>

<p>Listing#new</p>
<p>Find me in app/views/listing/new.html.erb</p>

app/views/listings/show.html.erb
<h2>This is your newly created listing</h2>
<p> Title: <%= @listing.title %> </p>
<p> Address: <%= @listing.address %> </p>
<p> State: <%= @listing.state %> </p>
<p> City: <%= @listing.city %> </p>
<p> Zipcode: <%= @listing.zipcode %> </p>
<p> Country: <%= @listing.country %> </p>
<p> Pax: <%= @listing.pax %> </p>
<p> Bed Number: <%= @listing.bed_number %> </p>
<p> Room Number: <%= @listing.room_number %> </p>
<p> Property Type: <%= @listing.property_type %> </p>
<p> Description: <%= @listing.description %> </p>
<p> Price: <%= @listing.price %> </p>
<p>
  Photos: <% @listing.photos.each do |photo| %>
          <%= image_tag photo.medium, class: "img-response" %>
          <% end %>
</p>

<%= render "reservations/form" %>
<!-- render the form in the reservations/form -->

<p>Listing#show</p>
<p>Find me in app/views/listing/show.html.erb</p>