config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  # get 'reservations/:id/braintree/new' => "braintree#new", as: :new_braintree
  post 'braintree/checkout'
  get 'welcome/index'

  root "welcome#index"
  # get '/' => "welcome#index", as: 'root'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, controller: "listings", only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reservations, only: [:create, :index]
    # resources :reservations only: [:index,:create] # do that to show the reservations under listing/:id and create a reservation under listing/:id
  end

  resources :reservations, except: [:new, :create]
  # resources :reservations only: [:show, :edit, :update] # to show the reservation page, to edit and update reservation

  resources :users, controller: "users", only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :password, # user can only have one password therefor resource without a s
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings # user can have a lot of lisitings therefore resources with a s
    resources :reservations, only: [:index] # to show user's reservations
  end



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
  has_many :listings, :dependent => :destroy # need to add in listings as you add in the listings table to have a user_id in the listing's table
  has_many :authentications, :dependent => :destroy
  mount_uploader :photo, PhotoUploader
  # serialize :photo, Array
  paginates_per 10

  def self.create_with_auth_and_hash(authentication, auth_hash)
      # byebug
      user = User.create!(firstname: auth_hash["info"]["first_name"], lastname: auth_hash["info"]["last_name"], email: auth_hash["info"]["email"])
      user.authentications << (authentication)
      return user
  end

  def fb_token
    x = self.authentications.where(:provider => :facebook).first
    return x.token unless x.nil?
  end

  def password_optional?
    true
  end

  # or can put a random password: '1234' in line 8

end

app/controllers/clearance/users_controller.rb
class Clearance::UsersController < Clearance::BaseController
  if respond_to?(:before_action)
    before_action :redirect_signed_in_users, only: [:create, :new]
    skip_before_action :require_login, only: [:create, :new], raise: false
    skip_before_action :authorize, only: [:create, :new], raise: false
  else
    before_filter :redirect_signed_in_users, only: [:create, :new]
    skip_before_filter :require_login, only: [:create, :new], raise: false
    skip_before_filter :authorize, only: [:create, :new], raise: false
  end

  def new
    @user = user_from_params
    render template: "users/new"
  end

  def create
    @user = user_from_params

    if @user.save
      sign_in @user
      redirect_back_or url_after_create
    else
      render template: "users/new"
    end
  end

  private

  def avoid_sign_in
    warn "[DEPRECATION] Clearance's `avoid_sign_in` before_filter is " +
      "deprecated. Use `redirect_signed_in_users` instead. " +
      "Be sure to update any instances of `skip_before_filter :avoid_sign_in`" +
      " or `skip_before_action :avoid_sign_in` as well"
    redirect_signed_in_users
  end

  def redirect_signed_in_users
    if signed_in?
      redirect_to Clearance.configuration.redirect_url
    end
  end

  def url_after_create
    Clearance.configuration.redirect_url
  end

  def user_from_params
    email = user_params.delete(:email)
    password = user_params.delete(:password)
    firstname = user_params.delete(:firstname)
    lastname= user_params.delete(:lastname)

    Clearance.configuration.user_model.new(user_params).tap do |user|
      user.email = email
      user.password = password
      user.firstname = firstname
      user.lastname = lastname
    end
  end

  def user_params
    params[Clearance.configuration.user_parameter] || Hash.new
  end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def index
    @user = User.all.page params[:page]
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user = current_user
    # byebug
    if @user.update(user_params)
      flash[:success] = "Successfully updated your profile"
      redirect_to @user
    else
      flash[:error] = "Error updating profile"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:firstname, :lastname, :email, :password, :photo)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :firstname %>
  <%= form.text_field :firstname, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :lastname %>
  <%= form.text_field :lastname, type: 'text' %>
</div>

<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

<div class="file-field">
  <%= form.label :photo %>
  <%= form.file_field :photo %>
</div>

app/views/users/edit.html.erb
<h1>Edit your profile here</h1>
<!-- need to put form_for and also render partial & object to render the _form.html -->
<!-- either use form_for in edit/new.html or in the _form.html for the render form to work -->
<%= form_for @user do |form| %>
  <%= render partial: 'form', object: form %>
  <%= form.submit "Update Profile!" %>
  <p> terms and conditions </p>
<% end %>
<p>Users#edit</p>

app/views/users/index.html.erb
<h1> All User's Listings </h1>
<table>
  <% @user.each do |u| %>
    <tr>
      <td> <%= u.firstname %> <%= u.lastname %> </td>
      <td> <%= u.email %> </td>
      <td> <%= link_to "Listings", user_listings_path(u) %> </td>
      <% if current_user.email == "chewbacca@email.com" || "yodamaster@email.com" %>
      <td> <%= link_to "Delete", user_path(u), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= paginate @user %>

<!-- <p>Users#index</p>
<p>Find me in app/views/users/index.html.erb</p> -->

<!-- anyone also can view the listing and edit, how to make it only that user can edit their own listing? -->
<!-- ronin 179, 180 (pagination and authorization) -->

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>
  <%= form_for @user do |form| %>

    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <!-- <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div> -->
  <% end %>
</div>

app/views/users/show.html.erb
<h1> My Profile </h1>

<%= link_to "My Listing", user_listings_path(current_user) %>
<%= link_to "My Reservation", user_reservations_path(current_user) %>
<%= link_to "Edit Profile", edit_user_path(current_user) %>

<p> Username : <%= @user.firstname %> <%= @user.lastname %> </p>
<p> My Email : <%= @user.email %> </p>
<p> My Photo : <%= form_for @user do |f| %>
               <%= image_tag @user.photo.medium %>
               <% end %>
</p>

<br>
<br>

<!-- <p>Users#show</p>
<p>Find me in app/views/users/show.html.erb</p> -->