config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  # get 'reservations/:id/braintree/new' => "braintree#new", as: :new_braintree
  post 'braintree/checkout'
  get 'welcome/index'

  root "welcome#index"
  # get '/' => "welcome#index", as: 'root'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, controller: "listings", only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reservations, only: [:create, :index]
    # resources :reservations only: [:index,:create] # do that to show the reservations under listing/:id and create a reservation under listing/:id
  end

  resources :reservations, except: [:new, :create]
  # resources :reservations only: [:show, :edit, :update] # to show the reservation page, to edit and update reservation

  resources :users, controller: "users", only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :password, # user can only have one password therefor resource without a s
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings # user can have a lot of lisitings therefore resources with a s
    resources :reservations, only: [:index] # to show user's reservations
  end



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :date_start ,presence: true
  validates :date_end ,presence: true
  validates :guest ,presence: true
  validate :check_overlapping_date

  belongs_to :user
  belongs_to :listing

  def check_overlapping_date

    # self is @reservation, and it's listing with all the reservations that have been made, put it in res and compare to the existing @reservation that is going to be made
    self.listing.reservations.each do |res|

      # loop the listing's reservations in res and compare it to self/@reservation in overlap? method
      if overlap?(self, res)
        return true # it will return true and stop the loop if it overlaps, then will go to error message
      end
    end
    return false # when it compares with all the reservation of the listing and there is no overlapping, then it will return false and make a reservation for the user
  end

  def overlap?(x,y)
    (x.date_start - y.date_end) * (y.date_start - x.date_end) > 0
  end

  # checking if compare this date with all the current existed reservations, once its overlap it will return true
  def check_overlapping_for_edit?(x,y) # instance method, so the self here refers to @reservation object
    self.listing.reservations.each do |res|
      if (x - res.date_end) * (res.date_start - y) > 0
        return true
      end
    end

    return false #means the equation is never > 0, means NO OVERLAP
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def create
    @reservation = Reservation.new(reservation_params)

    @reservation.user = current_user
    @reservation.listing_id = params["listing_id"]
    if @reservation.check_overlapping_date == false
      @reservation.save
      flash[:reserve] = "Thank you for your reservation!"

      # the two below are for Action Mailer to send email to customers (at app/jobs/reservation_job.rb)
      # deliver_later will put the email delivery job queqe to sidekiq and deliver later, while continue the page without having to wait email sent then only load to next page.
      ReservationMailer.booking_email_to_customer(current_user.id, @reservation.listing.user_id, @reservation.id).deliver_later # this is to send confirmation email to customer after they have made a booking.
      ReservationMailer.booking_email_to_host(current_user.id, @reservation.listing.user_id, @reservation.id).deliver_later # this is to send notification email to the host for whoever customers who have made any bookings on their listing.

      # below this is for Active Jobs to send email or in future any other jobs to customers that act as a background job to send email asynchronously
      # ReservationJob.perform_later(current_user.id, @reservation.listing.user_id, @reservation.id)

      redirect_to @reservation # redirect_to 'show' page
    else
      flash[:error] = "Error, the dates you choose is not available"
      # render 'listings/show'
      redirect_to listing_path(@reservation.listing) # redirect back to 'create', it will not clear ur cache
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    # convert date in String format to Date format, to conver back to String format, put .to_s
    # in create, the reservation_params with the date keyed in will be in date format because in schema, I have set date_start and date_end to Date format
    # but in edit, the newly key in date is in string format so need to change it to Date format in order to compared it with the res
    # can check the format in irb, put .class
    # a, b is arguments to be put in for new edited date_start and date_end, so that can compare with self, and res
    # if put self, will always comapare it with the existing reserved date
    # a = Date.strptime(params[:reservation][:date_start], '%Y/%m/%d') # newly filled in date_start
    # b = Date.strptime(params[:reservation][:date_end], '%Y/%m/%d') # newly filled in date_end
    x = params[:reservation][:date_start].to_date # .to_date is to change the date format
    y = params[:reservation][:date_end].to_date # .to_date is to change the date format

    if @reservation.check_overlapping_for_edit?(x,y) == false
      @reservation.update(reservation_params) # strong params, user can only key in the params require so hackers cannot hack
      flash[:success] = "Successfully updated your reservation"
      redirect_to @reservation # redirect to controller show to show the new listing
    else
      flash[:error] = "Error, please try again."
      render :edit # render to controller 'edit.html'
      # the difference between render and redirect_to is render is to the page, redirect_to is to the path,m it will go to config/routes.rb it will check out what path it is, and go to respective controller action
    end
  end

  def destroy
    @rervation = Reservation.find(params[:id]) # find the users/user_id/listings/:id
    @reservation.destroy
    flash[:delete] = "Successfully deleted!"
    redirect_to reservations_path
  end

private
  def reservation_params
    # first method with listing_id
    params.require(:reservation).permit(:date_start, :date_end, :guest, :listing_id)
    # second method without listing_id
    # params.require(:reservation).permit(:date_start, :date_end, :guest)
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<h3> Reservation for your next stay! </h3>

<%= form_for [@listing,@reservation] do |form| %>
<p>
  <div>
    <%= form.label "Start Date: " %>
      <%= form.text_field :date_start, class:"datepicker", placeholder: "YYYY/MM/DD", autocomplete: "off" %>
      <!-- autocomplete: "off" means to turn off the autocomplete in the form -->
  </div>

  <div>
    <%= form.label "End Date: " %>
    <%= form.text_field :date_end, class:"datepicker", placeholder: "YYYY/MM/DD", autocomplete: "off" %>
  </div>

  <div>
    <%= form.label "Number of Guest: " %>
    <%= form.text_field :guest %>
    <!-- need to put listing_id because they don't know which listing_id this reservation belongs to -->
  </div>
</p>

<p>
  <%= form.submit "Book!" %>
</p>

<% end %>

app/views/reservations/edit.html.erb
<h1> Edit your reservation </h1>

<%= render 'form' %>

<p>Reservations#edit</p>
<p>Find me in app/views/reservations/edit.html.erb</p>

app/views/reservations/index.html.erb
<h1> My Reservations </h1>

<table class="table">
  <tr>
    <th>Listing</th>
    <th>Date start</th>
    <th>Date end</th>
    <th>Number of guest</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @reservations.each do |r| %>
    <tr>
      <td> <%= r.listing.title %> </td>
      <td> <%= r.date_start%> </td>
      <td> <%= r.date_end %> </td>
      <td> <%= r.guest %> </td>
      <td> <%= r.listing.price %> </td>
      <td> <%= link_to "Edit", edit_reservation_path(r) %> </td>
      <td> <%= link_to "Delete", reservation_path(r), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
      <td> <%= link_to "Make Payment", braintree_new_path(r) %> </td>
    </tr>
  <% end %>
</table>

<p>Reservations#index</p>
<p>Find me in app/views/reservations/index.html.erb</p>

app/views/reservations/show.html.erb
<h1>This is your reservation</h1>
<p> Start Date: <%= @reservation.date_start %> </p>
<p> End Date: <%= @reservation.date_end %> </p>
<p> Guest Number: <%= @reservation.guest %> </p>

<!-- need to use link_to to go to the payment page -->
<%= link_to ("Make Payment"),  braintree_new_path(:id => @reservation.id), method: :get %>

<p>Reservations#show</p>
<p>Find me in app/views/reservations/show.html.erb</p>