config/routes.rb
Rails.application.routes.draw do

  get 'braintree/new'
  # get 'reservations/:id/braintree/new' => "braintree#new", as: :new_braintree
  post 'braintree/checkout'
  get 'welcome/index'

  root "welcome#index"
  # get '/' => "welcome#index", as: 'root'

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]
  resources :listings, controller: "listings", only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :reservations, only: [:create, :index]
    # resources :reservations only: [:index,:create] # do that to show the reservations under listing/:id and create a reservation under listing/:id
  end

  resources :reservations, except: [:new, :create]
  # resources :reservations only: [:show, :edit, :update] # to show the reservation page, to edit and update reservation

  resources :users, controller: "users", only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :password, # user can only have one password therefor resource without a s
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
    resources :listings # user can have a lot of lisitings therefore resources with a s
    resources :reservations, only: [:index] # to show user's reservations
  end



  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Load the Client component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

  <!-- Load the Hosted Fields component. -->
  <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>
  <!-- already install gem bootstrap so no need to put here to link -->
  <!-- this one is css -->
  <script
  src="https://code.jquery.com/jquery-3.2.1.js"
  integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
  crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks': 'reload' %>
  <!-- this one is javascript -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>


</head>
<body>
  <div id="header">
    <% if signed_in? -%>
      <%= button_to t(".sign_out"), sign_out_path, method: :delete %>
      <%= button_to ("Back"),  root_path, method: :get %>
    <% else -%>
<!-- the t translate to the user's language by defaut, is a rails ways -->
      <%= link_to t(".sign_in"), sign_in_path %>
    <% end -%>
  </div>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="flash_<%= key %>"><%=h value %></div>
    <% end %>
  </div>
<!-- make it a button for 'Back', method by default is POST, so change the method to get -->

  <%= yield %>
</body>
</html>